name: istu_map
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  app_theme:
    path: packages/app_theme
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_inappwebview: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geolocator: ^11.0.0
  get_it: ^7.7.0
  http_parser: ^4.0.2
  image_map:
    path: packages/image_map
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.3.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.1
  path_drawing: ^1.0.1
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ">=7.0.0 <8.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
