name: istu_map
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_inappwebview: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geolocator: ^11.0.0
  get_it: ^7.7.0
  http_parser: ^4.0.2
  image_map:
    path: packages/image_map
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.1
  path: ^1.9.0
  path_drawing: ^1.0.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ">=7.0.0 <8.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/icon/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: Cuprum
      fonts:
        - asset: assets/fonts/cuprum/Cuprum-Regular.ttf
          weight: 400
        - asset: assets/fonts/cuprum/Cuprum-Medium.ttf
          weight: 500
        - asset: assets/fonts/cuprum/Cuprum-Semibold.ttf
          weight: 600
        - asset: assets/fonts/cuprum/Cuprum-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
